### ISSUE TITLE
error running evolutionary_agent_w_crossover

### ISSUE THREAD

**Issue by q-learning-trader** [entrpn/fingym#5]
Hi, nice work, thanks for sharing.
I am getting the following error.
I think output_probabilities needs to be renormalized.

```
***** agent score *****
score:  99302.44000000003
score:  189596.57999999993
score:  279890.71999999986
***** agent score *****
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/data/projects/fingym/gym/examples/agents/evolutionary_agent_w_crossover.py", line 278, in <module>
    rewards = run_agents_n_times(env,agents,3) # average of x times
  File "/home/data/projects/fingym/gym/examples/agents/evolutionary_agent_w_crossover.py", line 148, in run_agents_n_times
    avg_score.append(return_average_score(env, agent, runs))
  File "/home/data/projects/fingym/gym/examples/agents/evolutionary_agent_w_crossover.py", line 141, in return_average_score
    score += run_agent(env, agent)
  File "/home/data/projects/fingym/gym/examples/agents/evolutionary_agent_w_crossover.py", line 130, in run_agent
    action = agent.act(state)
  File "/home/data/projects/fingym/gym/examples/agents/evolutionary_agent_w_crossover.py", line 74, in act
    action = np.random.choice(range(self.action_size),1,p=output_probabilities).item()
  File "mtrand.pyx", line 926, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

**Comment by entrpn** [comment]
hey, I think this is a numpy issue (https://github.com/numpy/numpy/pull/6131)

Is fixed in the multi_env_evo_agent as follows:

```
    def act(self, state, model):
        self.state_fifo.append(state)

        # do nothing for the first time frames until we can start the prediction
        if len(self.state_fifo) < self.time_frame:
            return np.zeros(2)
        
        state = np.array(list(self.state_fifo))
        state = np.reshape(state,(self.state_size*self.time_frame,1))

        output_probabilities = model.predict_on_batch(state.T)[0]
        output_probabilities = np.array(output_probabilities)
        output_probabilities /= output_probabilities.sum()
        try:
            action = np.random.choice(range(self.action_size),1,p=output_probabilities).item()
        except:
            print('output probabilities: ', output_probabilities)
            action = np.zeros(2)
        env_action = self._nn_action_to_env_action(action)
        return env_action
```

not the cleanest, but works. We'll put a fix for this agent.

**Comment by entrpn** [comment]
I put a fix in https://github.com/entrpn/fingym/commit/e519dbb3aa52604b6d8f21675264537c5b4f80ce

Let me know if you have any other issues.
